
%--------------------------------------------------------------------------
%Copyright (c) 2015 by Saber Elsayed
%Cell based initialization
%--------------------------------------------------------------------------
%Author information
%Saber Elsayed
%UNiversity of New South Wales Canberra
%s.elsayed@adfa.edu.au
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
%--- this is an example to plot the fitness values of initial points ------
%---- generated by the proposed method ------------------------------------
%---- problem: Schwefwl2


function  PlotInitPop
clc;

xmaxlim= [100 10 100 100 30 100 1.28 500 5.12 32 600 50 50];
xminlim= [-100 -10 -100 -100 -30 -100 -1.28 -500 -5.12 -32 -600 -50 -50];

for I_fno = 8 : 8
    % Define the dimension of the problem
    n = 30;
    xmin=xminlim(I_fno)*ones(1,n);    xmax=xmaxlim(I_fno)*ones(1,n);
    lu=[xmin; xmax];
    q=10; % default is 10 - change
    [popold_orig] = Cell_Init_x_mex (lu(1, :),lu(2, :),n,q);
    
    valParents_orig = eval(popold_orig,n,size(popold_orig,1));
    plot(valParents_orig,'DisplayName','Proposed','Color',[1 0 0]);
    ylabel('f(x)');
    xlabel('solutions');
    ylabel('f(x)');
    
end

%% ----- Fitness Function Evaluations

function f = eval (x,n,popsize)
% Schwefwl2.26
for i=1:popsize
    f(i,1) =-1* sum((x(i,:)).*sin(sqrt(abs(x(i,:)))));%% 418.98288727243369*n
end
